Make self.memport instead of all the elements
Still no idea why I can't stick this in the top with everything else.
With that I just get

    $ make -j1
    mkdir -p check/
    obj/venv/bin/python rtl/top.py --output-vcd check/nop-pass.vcd --bootrom-elf obj/tests/nop-pass.elf
    Traceback (most recent call last):
      File "/scratch/poc/rtl/top.py", line 63, in <module>
        sim = Simulator(dut)
      File "/scratch/poc/obj/venv/lib/python3.10/site-packages/amaranth/sim/core.py", line 34, in __init__
        self._design   = Fragment.get(fragment, platform=None).prepare()
      File "/scratch/poc/obj/venv/lib/python3.10/site-packages/amaranth/hdl/_ir.py", line 63, in get
        new_obj = obj.elaborate(platform)
      File "/scratch/poc/rtl/core.py", line 34, in elaborate
        frontend.icache_refill.req.ready.eq(self.memport.req.ready),
    AttributeError: 'Core' object has no attribute 'memport'
    make: *** [Makefile:27: check/nop-pass.vcd] Error 1

which doesn't make any sense to me.

Signed-off-by: Palmer Dabbelt <palmer@rivosinc.com>